FROM openjdk:17
ADD ../target/hello-ga-docker-heroku-0.0.1-SNAPSHOT.jar hello-ga-docker-heroku-0.0.1-SNAPSHOT.jar
CMD java -Dserver.port=$PORT $JAVA_OPTS -jar hello-ga-docker-heroku-0.0.1-SNAPSHOT.jar
